[target.thumbv7em-none-eabihf]
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip stm32f767zi"

rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"
